site_name: AWSIM

theme:
  name: material
  font:
    text: Roboto
  features:
    - toc.follow
    - navigation.sections
    - content.tabs.link
    - content.code.copy
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    # - navigation.expand
  palette:
    scheme: slate
  icon:
    repo: fontawesome/brands/github
    
  logo:
  custom_dir: docs/Home/overrides

extra_css:
  - stylesheets/extra.css
  - stylesheets/lightbox.min.css

extra:
  generator: false

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - javascripts/lightbox-plus-jquery.min.js
  - javascripts/lightbox-settings.js

markdown_extensions:
  - tables
  - admonition
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight :  
      anchor_linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true


repo_url: https://github.com/tier4/AWSIM
repo_name: tier4/AWSIM

nav:
  - Home: index.md
  - Getting started:
    - Quick start demo: GettingStarted/QuickStartDemo/index.md
    - Demo details: GettingStarted/DemoDetails/index.md
    - AWSIM concept: GettingStarted/AWSIMConcept/index.md
    - Advanced:
      - Awsim rviz plugins: GettingStarted/Advanced/AwsimRvizPlugins/index.md
      - Logitech G29: GettingStarted/Advanced/LogitechG29/index.md
      - UsingOpenScenario: GettingStarted/Advanced/UsingOpenScenario/index.md
  - Developer guide:
    - Prerequisites: DeveloperGuide/Prerequisites/index.md
    - Setup unity project: DeveloperGuide/SetupUnityProject/index.md
    - Setup vscode: DeveloperGuide/SetupVscode/index.md
    - Architecture: DeveloperGuide/Architecture/index.md
    - Demo scenes: DeveloperGuide/DemoScenes/index.md    
    - Coding standards: DeveloperGuide/CodingStandards/index.md
    - Git: DeveloperGuide/Git/index.md
    - External libraries: DeveloperGuide/ExternalLibraries/index.md
    - Directory: DeveloperGuide/Directory/index.md
    - Switch SRP: DeveloperGuide/SwitchSrp/index.md
    - Fork repository: DeveloperGuide/ForkRepository/index.md
    - Documentation: DeveloperGuide/Documentation/index.md
    - Trouble shooting: DeveloperGuide/TroubleShooting/index.md
    - How to contribute: DeveloperGuide/HowToContribute/index.md
    - Layer:
      - UI: DeveloperGuide/Layer/UI/index.md
      - Usecase:
        - Awsim Rviz Plugins: DeveloperGuide/Layer/Usecase/AwsimRvizPlugins/index.md
        - Pcd generation: DeveloperGuide/Layer/Usecase/PcdGeneration/index.md
        - Traffic Simulation: DeveloperGuide/Layer/Usecase/TrafficSimulation/index.md
        - Scenario Simulator Connection: DeveloperGuide/Layer/Usecase/ScenarioSimulatorConnection/index.md
      - Entity:
        - Vehicle:
          - Accel vehicle: DeveloperGuide/Layer/Entity/Vehicle/AccelVehicle/index.md
          - Pose vehicle: DeveloperGuide/Layer/Entity/Vehicle/PoseVehicle/index.md
        - Sensors:
          - LiDAR & Radar sensor: DeveloperGuide/Layer/Entity/Sensor/LidarAndSensor/index.md
          - Camera sensor: DeveloperGuide/Layer/Entity/Sensor/CameraSensor/index.md
          - IMU sensor: DeveloperGuide/Layer/Entity/Sensor/ImuSensor/index.md
          - GNSS sensor: DeveloperGuide/Layer/Entity/Sensor/GnssSensor/index.md
        - Infra:
          - Traffic light: DeveloperGuide/Layer/Entity/Infra/TrafficLight/index.md
      - Common:
        - ROS2: DeveloperGuide/Layer/Common/Ros2/index.md
    - Experimental:
      - Running headless: DeveloperGuide/Experimental/RunningHeadless/index.md
  - Downloads: Downloads/index.md
  - License: License/index.md
  - Contact: Contact/index.md
