site_name: AWSIM document

repo_url: https://github.com/tier4/AWSIM

theme:
  name: material
  palette:
    primary: indigo
  features:
    - navigation.sections
    - content.tabs.link
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - tables
  - admonition
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true 
  - attr_list

nav:
  - Home: index.md

  - Getting started:
    - Quick Start Demo: GettingStarted/QuickStartDemo/index.md
    - Setup Unity Project: GettingStarted/SetupUnityProject/index.md

  - Project guide:
    - Directory: ProjectGuide/Directory/index.md
    - Git Branch: ProjectGuide/GitBranch/index.md
    - External Libraries: ProjectGuide/ExternalLibraries/index.md

  - Components:
    - Vehicle:
      - AWSIM Vehicle: Components/Vehicle/AWSIMVehicle/index.md
      - Add New Vehicle: Components/Vehicle/AddVehicle/index.md
    - Sensors:
      - LiDAR Sensor: Components/Sensors/LiDARSensor/index.md
      - Camera Sensor: Components/Sensors/CameraSensor/index.md
      - IMU Sensor: Components/Sensors/IMUSensor/index.md
      - GNSS Sensor: Components/Sensors/GNSSSensor/index.md
    - Environment:
      - AWSIM Environment: Components/Environment/AWSIMEnvironment/index.md
      - Add New Environment: Components/Environment/AddNewEnvironment/index.md
      - PointCloudMapper: Components/Environment/PointCloudMapper/index.md
    - Traffic:
      - Random Traffic:
        - Random Traffic Simulator: Components/Traffic/RandomTraffic/RandomTrafficSimulator/index.md
        - Add Random Traffic Environment: Components/Traffic/RandomTraffic/AddRandomTrafficEnvironment/index.md
    - ROS2:
      - ROS2 topic list: Components/ROS2/ROS2TopicList/index.md
      - Add custom ROS2 msg type: Components/ROS2/AddCustomROS2MessageType/index.md

  - Developer guide:
    - Trouble shooting: DeveloperGuide/TroubleShooting/index.md
    - Documentation: DeveloperGuide/Documentation/index.md
    - License : DeveloperGuide/License/index.md
    - Contact : DeveloperGuide/Contact/index.md
